name: Lint and Commit

on:
  push:
    branches:
      - "**" # Run on push to any branch

jobs:
  lint-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0 # Ensure all history is fetched for commits

      - name: Check if commit is by GitHub Actions bot
        id: check-commit
        run: |
          if [[ "$(git log -1 --pretty=%an)" == "github-actions[bot]" ]]; then
            echo "Commit was made by GitHub Actions bot, exiting..."
            exit 0
          fi

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        timeout-minutes: 5
        with:
          python-version-file: .python-version
          cache: "pip"
          cache-dependency-path: |
            pip-requirements.txt
            dev-requirements.txt

      - name: Install Python dependencies
        run: |
          pip install -r pip-requirements.txt
          pip install -r dev-requirements.txt

      # - name: Format Python imports
      #   run: |
      #     isort $(git ls-files "*.py")

      # - name: Format and Lint Python
      #   run: |
      #     black $(git ls-files "*.py")
      #     autopep8 --in-place --aggressive --ignore=E721 $(git ls-files "*.py")

      # - name: Lint with flake8
      #   continue-on-error: true
      #   run: |
      #     flake8 $(git ls-files "*.py")

      # - name: Lint with pylint
      #   continue-on-error: true
      #   run: |
      #     pylint $(git ls-files "*.py")

      #   - name: Setup Node.js
      #     uses: actions/setup-node@v4.0.2
      #     with:
      #       node-version: "20" # Specify the Node.js version you are using
      #       cache: "npm"

      #   - name: Install Node.js dependencies
      #     run: |
      #       npm install

      #   - name: Lint TypeScript/Next.js
      #     continue-on-error: true
      #     run: |
      #       npm run lint

      # - name: Commit changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add --all
      #     git reset .github/workflows  # Exclude workflow files from the commit
      #     if git diff-index --quiet HEAD; then
      #       echo "No changes to commit"
      #     else
      #       git commit -m "Apply auto formatting and lint fixes"
      #       git push origin HEAD:${{ github.ref }}
      #     fi
